Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -35,8 +35,9 @@ jobs:
       - name: Generate Coverage Report
         run: |
           cd build
-          lcov --capture --directory . --output-file coverage.info --ignore-errors mismatch,source --rc lcov_branch_coverage=1 --rc geninfo_unexecuted_blocks=1 --exclude '*/tests/*' --exclude '*/_deps/*'
-          lcov --remove coverage.info 'tests/*' '_deps/*' '/usr/*' --output-file coverage.info
+          lcov --capture --directory . --output-file coverage.info --ignore-errors mismatch,source,unused --rc branch_coverage=1 --rc geninfo_unexecuted_blocks=1 --exclude '*tests*' --exclude '*_deps*'
+          lcov --remove coverage.info '*tests*' '*_deps*' '/usr/*' --output-file coverage.info
+          lcov --list coverage.info || echo "Failed to list coverage.info"
 
       - name: Check Coverage File
         run: |
